language: generic
sudo: required 
services: 
  - docker 

before_install: 
  - docker build -t 240496/docker-janna -f Dockerfile.dev .

script: 
   - docker run -e CI=true 240496/docker-janna npm run test

deploy: 
  provider: elasticbeanstalk 
  region: "us-east-1"
  app: "docker-janna"
  env: "DockerJanna-env"
  bucket_name: "elasticbeanstalk-us-east-1-436835035193"
  bucket_path: "docker-janna"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY                 
  secret_access_key: $AWS_SECRET_KEY  